//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LacmusApp.Avalonia.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Settings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Settings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("LacmusApp.Avalonia.Properties.Settings", typeof(Settings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NeedRestart {
            get {
                return ResourceManager.GetString("NeedRestart", resourceCulture);
            }
        }
        
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        public static string MlModel {
            get {
                return ResourceManager.GetString("MlModel", resourceCulture);
            }
        }
        
        public static string InstalledModels {
            get {
                return ResourceManager.GetString("InstalledModels", resourceCulture);
            }
        }
        
        public static string AvailableModels {
            get {
                return ResourceManager.GetString("AvailableModels", resourceCulture);
            }
        }
        
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        public static string BoundingBoxColour {
            get {
                return ResourceManager.GetString("BoundingBoxColour", resourceCulture);
            }
        }
        
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        public static string MlModelHadding {
            get {
                return ResourceManager.GetString("MlModelHadding", resourceCulture);
            }
        }
        
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        public static string InferenceType {
            get {
                return ResourceManager.GetString("InferenceType", resourceCulture);
            }
        }
        
        public static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        public static string SupportedOs {
            get {
                return ResourceManager.GetString("SupportedOs", resourceCulture);
            }
        }
        
        public static string Threshold {
            get {
                return ResourceManager.GetString("Threshold", resourceCulture);
            }
        }
        
        public static string RepositoryUrl {
            get {
                return ResourceManager.GetString("RepositoryUrl", resourceCulture);
            }
        }
        
        public static string MlModelsHadding {
            get {
                return ResourceManager.GetString("MlModelsHadding", resourceCulture);
            }
        }
        
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        public static string InstallButton {
            get {
                return ResourceManager.GetString("InstallButton", resourceCulture);
            }
        }
        
        public static string RemoveButton {
            get {
                return ResourceManager.GetString("RemoveButton", resourceCulture);
            }
        }
        
        public static string ActivateButton {
            get {
                return ResourceManager.GetString("ActivateButton", resourceCulture);
            }
        }
    }
}
